name: Generate docs

on:
  push:
    branches: [main]

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    name: Generate docs with pandvimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: snippet-converter
          description: "Convert snippets to the format of your choice"
          pandoc: doc/documentation.md
          version: "NVIM v0.7"
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto generate docs"
          title: "Auto generate docs"
